from app import create_app
from app.extensions import socketio

app = create_app()

if __name__ == "__main__":
    print("\n========================================")
    print("  MAGGIE Ground Station Server")
    print("  REXUS Programme — v0.3.0")
    print("========================================")
    print("  ── Auth ──────────────────────────────")
    print("  POST /api/auth/login        — Login")
    print("  POST /api/auth/register     — Register (admin)")
    print("  GET  /api/auth/me           — Current user")
    print("  ── Health ────────────────────────────")
    print("  GET  /api/health            — Health check")
    print("  ── Telemetry (HTTP) ──────────────────")
    print("  POST /api/telemetry         — Write data point")
    print("  POST /api/telemetry/batch   — Write multiple points")
    print("  GET  /api/telemetry         — Query data points")
    print("  GET  /api/telemetry/ping    — InfluxDB status")
    print("  ── OBC Commands ──────────────────────")
    print("  POST /api/command/state     — Set mission state")
    print("  POST /api/command/mode      — Select operation mode")
    print("  POST /api/command/hrdm/deploy — Deploy HRDM")
    print("  POST /api/command/hrdm/lock — Lock HRDM")
    print("  POST /api/command/light     — Light on/off")
    print("  POST /api/command/arm/estop — Arm emergency stop")
    print("  ── OBC Status ────────────────────────")
    print("  GET  /api/obc/status        — Full OBC snapshot")
    print("  GET  /api/obc/flags         — RXSM flags")
    print("  GET  /api/obc/arm           — Robot arm status")
    print("  ── Real-time (Socket.IO) ─────────────")
    print("  WS   /socket.io/           — Telemetry stream")
    print("  ── OBC UDP-Interface ─────────────────")
    print("  UDP  :9000  ← OBC packets  (64 Bytes)")
    print("  UDP  :9001  → OBC commands  (16 Bytes)")
    print("  Running on http://localhost:3000")
    print("========================================\n")

    socketio.run(app, host="0.0.0.0", port=3000, debug=True)
